version: "3"
services:
    nginx:
        image: nginx:stable-alpine
        ports:
            - "3000:80"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    express-app:
        build: .
        
        environment: 
            - PORT=3000

        depends_on:
            - mongo    
    mongo:
        image: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=inyuusha
            - MONGO_INITDB_ROOT_PASSWORD=mypass       
        volumes: 
            - mongo-db:/data/db    
    redis:
        image: redis        
volumes:
    mongo-db:            