version: "3"
services:
    express-app:
        build: .
        ports:
            - "3000:3000"
        depends_on:
            - mongo    
    mongo:
        image: mongo
        environment:
            - MONGO_INITDB_ROOT_USERNAME=inyuusha
            - MONGO_INITDB_ROOT_PASSWORD=mypass       
        volumes: 
            - mongo-db:/data/db    
    redis:
        image: redis        
volumes:
    mongo-db:            